- name: EC2インスタンスを作成
  ec2:
    image: "{{ item.value.ami_image }}"
    instance_type: "{{ item.value.instance_type }}"
    region: "{{ my_vars.aws.common.region }}"
    key_name: "{{ item.value.key_name }}"
    group: "{{ item.value.security_group }}"
    instance_tags: "{{ item.value.tags }}"
#    assign_public_ip: "{{ item.value.assign_public_ip }}"
#    private_ip: "{{ item.value.private_ip | default(omit) }}"
    wait: yes
    wait_timeout: 300
#    count_tag:
#      Name: "{{ item.value.tags.Name }}"
#    exact_count: 1
#    user_data: |
#      #!/bin/bash
#      # 初期設定スクリプトなど
  with_dict: "{{ my_vars.aws.ec2 }}"
  register: ec2_result
  when: my_vars.aws.ec2 is defined

- debug: var=ec2_result

- name: yum update
  yum: state=latest name=*
